### PR TITLE
chore(google): Bump google compute dependencies

### PR DESCRIPTION
**Pull request by ezimanyi**
We're currently using an alpha version of the client library for GCE from December 2017; all of the features we were using are in the current version of the beta client library.

Given that we aren't using any alpha features, let's move to the beta version of the library. If we want to support an alpha feature, it's easy to move back to the alpha version.

### CODE REVIEW

**Comment by ezimanyi** [comment]
@ttomsu @duftler @jtk54 : Interested in thoughts about moving to the beta version of the library.  When doing the upgrade, I tested, and we are currently not using anything exclusively in the alpha version.

It's easy to move back to the alpha library if we want in the future, but this will make it a bit more deliberate if we do add in future alpha-only features.

**Comment by jtk54** [comment]
I think given we could compile with all the beta models etc in Clouddriver we are likely OK to use the beta lib.

**Comment by ttomsu** [comment]
IIUC, the version of the client library is independent of the API version the client library hits. I'm not opposed to the change, but I don't know if or what benefit it brings either.

**Comment by ezimanyi** [comment]
Yes, this will not affect the actual endpoint we hit, only the generated client library we are using to generate calls to it.

Agreed the benefit is not huge, but I think there is a small benefit.  We had discussed moving away from hitting the alpha endpoint except on calls that actually need it for stability reasons.  By moving the library to beta and ensuring it compiles (as it does) we can start from a known state where nothing needs to hit the alpha endpoint.

**Comment by duftler** [comment]
I agree it makes sense to move to the beta library if we don't need any of the alpha features.

**Pull request merged**
